# Generated by Django 4.0.1 on 2022-01-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('steps', '0011_alter_steps_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='steps.goals')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
