# Generated by Django 4.0.1 on 2022-01-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='goal',
        ),
    ]
