# Generated by Django 4.0.1 on 2022-01-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goals',
            options={'verbose_name_plural': 'Goals'},
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='sumit_date',
            new_name='submit_date',
        ),
    ]
