# Generated by Django 4.0.1 on 2022-01-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_alter_goals_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='first_name',
            field=models.CharField(default='now', max_length=255),
        ),
    ]
