# Generated by Django 4.0.1 on 2022-01-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_goals_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
