# Generated by Django 4.0.1 on 2022-01-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_alter_goals_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField()),
                ('submit_date', models.DateTimeField(verbose_name='date submitted')),
                ('first_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Steps',
            },
        ),
    ]
