# Generated by Django 4.0.1 on 2022-01-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0008_alter_goals_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='steps.goals'),
        ),
    ]
