# Generated by Django 4.0.1 on 2022-01-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0012_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='step',
            field=models.IntegerField(),
        ),
    ]
