# Generated by Django 4.0.1 on 2022-01-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0013_alter_target_goal_alter_target_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='step',
            field=models.IntegerField(null=True),
        ),
    ]
