# Generated by Django 4.0.1 on 2022-01-19 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0014_alter_target_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steps',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='step',
            new_name='steps',
        ),
        migrations.AddField(
            model_name='target',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='goal_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 20, 48, 7, 749672, tzinfo=utc), verbose_name='goal submitted'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='goal',
            field=models.IntegerField(null=True),
        ),
    ]
