# Generated by Django 4.0.1 on 2022-01-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0016_alter_target_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='goal_submitted',
            field=models.DateTimeField(null=True, verbose_name='goal submitted'),
        ),
    ]
