# Generated by Django 4.0.1 on 2022-01-24 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steps', '0017_alter_target_goal_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField(null=True, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Steps',
            },
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
        migrations.AlterField(
            model_name='target',
            name='steps',
            field=models.IntegerField(default=0, null=True, verbose_name='Total Steps'),
        ),
        migrations.AlterField(
            model_name='target',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
